apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hr-for-impact.fr
  namespace: cert-manager
spec:
  secretName: hr-for-impact.fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hr-for-impact.fr
  dnsNames:
  - hr-for-impact.fr
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cms.hr-for-impact.fr
  namespace: cert-manager
spec:
  secretName: cms.hr-for-impact.fr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cms.hr-for-impact.fr
  dnsNames:
  - cms.hr-for-impact.fr